#!/usr/bin/env python3
"""Test-read ledger: every result file that contains evaluation-suite outputs, with its SHA-256,
modification time and the suites it covers. Output: results/ledger/test_read_ledger.jsonl (+ .md).

A "test read" is any file that holds scores or probabilities for a held-out suite (td_test,
kevT_test, kevT_dev, kevT9_dev, jb_*, DeepSWE held-out, typed-decisions test in cycle 2-4 runs).
The purpose column comes from the directory, cross-checked against README.md. Selection runs that
only touch dev suites are listed separately so that omissions are visible.
"""
import datetime as dt
import glob
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TEST = {"td_test", "kevT_test", "kevT_dev", "kevT9_dev", "jb_original", "jb_easy", "jb_hard", "test"}
PURPOSE = {
    "results/pointer": "one-time final eval of a pointer (MiDM) model",
    "results/probs": "probability dump; re-reads suites for cascade/OOD/stats analysis (no selection)",
    "results/seeds": "multi-seed final eval",
    "results/tta": "TTA dev-only check",
    "results/multi": "frozen-head multi-benchmark (selection files read dev only; FINAL = one-time)",
    "results/search": "frozen-head CV search (FINAL_test = one-time)",
    "results/stage_c": "stage-C adapter composition (dev/select suites only)",
    "results": "cycle-1/2 artefacts",
}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def suites_of(p):
    if p.endswith(".jsonl"):
        s = set()
        with open(p, encoding="utf-8") as f:
            for line in f:
                try:
                    s.add(json.loads(line).get("suite"))
                except ValueError:
                    pass
        return sorted(x for x in s if x)
    try:
        d = json.load(open(p, encoding="utf-8"))
    except (ValueError, UnicodeDecodeError):
        return []
    if isinstance(d, dict):
        if "eval" in d and isinstance(d["eval"], dict):
            return sorted(d["eval"])
        if "test" in d or "test_acc_ensemble" in d:
            return ["test"]
        if "selectors" in d:
            return ["deepswe_heldout38"]
    return []


def main():
    out_dir = os.path.join(HERE, "results", "ledger")
    os.makedirs(out_dir, exist_ok=True)
    rows = []
    files = sorted(set(glob.glob(os.path.join(HERE, "results", "**", "*.json"), recursive=True)
                       + glob.glob(os.path.join(HERE, "results", "**", "*.jsonl"), recursive=True)))
    for p in files:
        rel = os.path.relpath(p, HERE).replace("\\", "/")
        if rel.startswith("results/ledger/") or rel.startswith("results/stats/"):
            continue
        su = suites_of(p)
        is_test = bool(set(su) & TEST) or "deepswe_heldout38" in su
        d = os.path.dirname(rel)
        purpose = PURPOSE.get(d, PURPOSE.get(d.split("/")[0] + "/" + d.split("/")[1] if "/" in d else d, "other"))
        rows.append({"file": rel, "sha256": sha(p), "mtime": dt.datetime.fromtimestamp(os.path.getmtime(p)).isoformat(timespec="seconds"),
                     "suites": su, "reads_held_out": is_test, "purpose": purpose})
    rows.sort(key=lambda r: r["mtime"])
    with open(os.path.join(out_dir, "test_read_ledger.jsonl"), "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    held = [r for r in rows if r["reads_held_out"]]
    lines = ["# Test-read ledger (auto-generated by build_ledger.py)", "",
             f"{len(held)} of {len(rows)} result files contain held-out suite outputs. Full list with SHA-256 in test_read_ledger.jsonl.", "",
             "| time | file | held-out suites | purpose |", "|---|---|---|---|"]
    for r in held:
        hs = ", ".join(s for s in r["suites"] if s in TEST or s == "deepswe_heldout38")
        lines.append(f"| {r['mtime']} | {r['file']} | {hs} | {r['purpose']} |")
    open(os.path.join(out_dir, "test_read_ledger.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"{len(held)} held-out-reading files of {len(rows)}")


if __name__ == "__main__":
    main()
